"""Add password reset fields

Revision ID: 09c52283cc1b
Revises: 5c91d66ac3e7
Create Date: 2025-07-30 12:40:43.617341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c52283cc1b'
down_revision = '5c91d66ac3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultima_conexion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('ultima_conexion')
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
